# coding: utf-8

"""
    BMLT

    BMLT Admin API Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bmlt_client.models.settings_update import SettingsUpdate

class TestSettingsUpdate(unittest.TestCase):
    """SettingsUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingsUpdate:
        """Test SettingsUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingsUpdate`
        """
        model = SettingsUpdate()
        if include_optional:
            return SettingsUpdate(
                google_api_key = '',
                change_depth_for_meetings = 56,
                default_sort_key = '',
                language = '',
                default_duration_time = '',
                region_bias = '',
                distance_units = '',
                meeting_states_and_provinces = [
                    ''
                    ],
                meeting_counties_and_sub_provinces = [
                    ''
                    ],
                search_spec_map_center_longitude = 1.337,
                search_spec_map_center_latitude = 1.337,
                search_spec_map_center_zoom = 56,
                number_of_meetings_for_auto = 56,
                auto_geocoding_enabled = True,
                county_auto_geocoding_enabled = True,
                zip_auto_geocoding_enabled = True,
                default_closed_status = True,
                enable_language_selector = True,
                include_service_body_email_in_semantic = True,
                bmlt_title = '',
                bmlt_notice = '',
                format_lang_names = bmlt_client.models.format_lang_names.formatLangNames()
            )
        else:
            return SettingsUpdate(
        )
        """

    def testSettingsUpdate(self):
        """Test SettingsUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
