# coding: utf-8

"""
    BMLT

    BMLT Admin API Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bmlt_client.models.settings_object import SettingsObject

class TestSettingsObject(unittest.TestCase):
    """SettingsObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingsObject:
        """Test SettingsObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingsObject`
        """
        model = SettingsObject()
        if include_optional:
            return SettingsObject(
                google_api_key = '',
                change_depth_for_meetings = 0,
                default_sort_key = '',
                language = 'en',
                default_duration_time = '01:00',
                region_bias = 'us',
                distance_units = 'mi',
                meeting_states_and_provinces = [],
                meeting_counties_and_sub_provinces = [],
                search_spec_map_center_longitude = -118.563659,
                search_spec_map_center_latitude = 34.235918,
                search_spec_map_center_zoom = 6,
                number_of_meetings_for_auto = 10,
                auto_geocoding_enabled = True,
                county_auto_geocoding_enabled = False,
                zip_auto_geocoding_enabled = False,
                default_closed_status = True,
                enable_language_selector = False,
                include_service_body_email_in_semantic = False,
                bmlt_title = '',
                bmlt_notice = '',
                format_lang_names = []
            )
        else:
            return SettingsObject(
        )
        """

    def testSettingsObject(self):
        """Test SettingsObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
