# coding: utf-8

"""
    BMLT

    BMLT Admin API Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.no_meeting_exists import NoMeetingExists
from openapi_client import configuration


class TestNoMeetingExists(unittest.TestCase):
    """NoMeetingExists unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
