# coding: utf-8

"""
    BMLT

    BMLT Admin API Documentation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.format_partial_update import FormatPartialUpdate
from openapi_client import configuration


class TestFormatPartialUpdate(unittest.TestCase):
    """FormatPartialUpdate unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
