# coding: utf-8

"""
    BMLT

    BMLT Admin API Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt

class RootServerBaseStatisticsServiceBodies(BaseModel):
    """
    RootServerBaseStatisticsServiceBodies
    """
    num_zones: StrictInt = Field(..., alias="numZones")
    num_regions: StrictInt = Field(..., alias="numRegions")
    num_areas: StrictInt = Field(..., alias="numAreas")
    num_groups: StrictInt = Field(..., alias="numGroups")
    __properties = ["numZones", "numRegions", "numAreas", "numGroups"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RootServerBaseStatisticsServiceBodies:
        """Create an instance of RootServerBaseStatisticsServiceBodies from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RootServerBaseStatisticsServiceBodies:
        """Create an instance of RootServerBaseStatisticsServiceBodies from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RootServerBaseStatisticsServiceBodies.parse_obj(obj)

        _obj = RootServerBaseStatisticsServiceBodies.parse_obj({
            "num_zones": obj.get("numZones"),
            "num_regions": obj.get("numRegions"),
            "num_areas": obj.get("numAreas"),
            "num_groups": obj.get("numGroups")
        })
        return _obj


