# coding: utf-8

"""
    BMLT

    BMLT Admin API Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist

class ServiceBodyPartialUpdate(BaseModel):
    """
    ServiceBodyPartialUpdate
    """
    parent_id: Optional[StrictInt] = Field(None, alias="parentId")
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    admin_user_id: Optional[StrictInt] = Field(None, alias="adminUserId")
    assigned_user_ids: Optional[conlist(StrictInt)] = Field(None, alias="assignedUserIds")
    url: Optional[StrictStr] = None
    helpline: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    world_id: Optional[StrictStr] = Field(None, alias="worldId")
    __properties = ["parentId", "name", "description", "type", "adminUserId", "assignedUserIds", "url", "helpline", "email", "worldId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ServiceBodyPartialUpdate:
        """Create an instance of ServiceBodyPartialUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ServiceBodyPartialUpdate:
        """Create an instance of ServiceBodyPartialUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ServiceBodyPartialUpdate.parse_obj(obj)

        _obj = ServiceBodyPartialUpdate.parse_obj({
            "parent_id": obj.get("parentId"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "type": obj.get("type"),
            "admin_user_id": obj.get("adminUserId"),
            "assigned_user_ids": obj.get("assignedUserIds"),
            "url": obj.get("url"),
            "helpline": obj.get("helpline"),
            "email": obj.get("email"),
            "world_id": obj.get("worldId")
        })
        return _obj


