# coding: utf-8

"""
    BMLT

    BMLT Admin API Documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SettingsObject(BaseModel):
    """
    SettingsObject
    """ # noqa: E501
    google_api_key: Optional[StrictStr] = Field(default=None, alias="googleApiKey")
    change_depth_for_meetings: Optional[StrictInt] = Field(default=None, alias="changeDepthForMeetings")
    default_sort_key: Optional[StrictStr] = Field(default=None, alias="defaultSortKey")
    language: Optional[StrictStr] = None
    default_duration_time: Optional[StrictStr] = Field(default=None, alias="defaultDurationTime")
    region_bias: Optional[StrictStr] = Field(default=None, alias="regionBias")
    distance_units: Optional[StrictStr] = Field(default=None, alias="distanceUnits")
    meeting_states_and_provinces: Optional[List[StrictStr]] = Field(default=None, alias="meetingStatesAndProvinces")
    meeting_counties_and_sub_provinces: Optional[List[StrictStr]] = Field(default=None, alias="meetingCountiesAndSubProvinces")
    search_spec_map_center_longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="searchSpecMapCenterLongitude")
    search_spec_map_center_latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="searchSpecMapCenterLatitude")
    search_spec_map_center_zoom: Optional[StrictInt] = Field(default=None, alias="searchSpecMapCenterZoom")
    number_of_meetings_for_auto: Optional[StrictInt] = Field(default=None, alias="numberOfMeetingsForAuto")
    auto_geocoding_enabled: Optional[StrictBool] = Field(default=None, alias="autoGeocodingEnabled")
    county_auto_geocoding_enabled: Optional[StrictBool] = Field(default=None, alias="countyAutoGeocodingEnabled")
    zip_auto_geocoding_enabled: Optional[StrictBool] = Field(default=None, alias="zipAutoGeocodingEnabled")
    default_closed_status: Optional[StrictBool] = Field(default=None, alias="defaultClosedStatus")
    enable_language_selector: Optional[StrictBool] = Field(default=None, alias="enableLanguageSelector")
    include_service_body_email_in_semantic: Optional[StrictBool] = Field(default=None, alias="includeServiceBodyEmailInSemantic")
    bmlt_title: Optional[StrictStr] = Field(default=None, alias="bmltTitle")
    bmlt_notice: Optional[StrictStr] = Field(default=None, alias="bmltNotice")
    format_lang_names: Optional[Dict[str, Any]] = Field(default=None, alias="formatLangNames")
    __properties: ClassVar[List[str]] = ["googleApiKey", "changeDepthForMeetings", "defaultSortKey", "language", "defaultDurationTime", "regionBias", "distanceUnits", "meetingStatesAndProvinces", "meetingCountiesAndSubProvinces", "searchSpecMapCenterLongitude", "searchSpecMapCenterLatitude", "searchSpecMapCenterZoom", "numberOfMeetingsForAuto", "autoGeocodingEnabled", "countyAutoGeocodingEnabled", "zipAutoGeocodingEnabled", "defaultClosedStatus", "enableLanguageSelector", "includeServiceBodyEmailInSemantic", "bmltTitle", "bmltNotice", "formatLangNames"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SettingsObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if default_sort_key (nullable) is None
        # and model_fields_set contains the field
        if self.default_sort_key is None and "default_sort_key" in self.model_fields_set:
            _dict['defaultSortKey'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SettingsObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "googleApiKey": obj.get("googleApiKey"),
            "changeDepthForMeetings": obj.get("changeDepthForMeetings"),
            "defaultSortKey": obj.get("defaultSortKey"),
            "language": obj.get("language"),
            "defaultDurationTime": obj.get("defaultDurationTime"),
            "regionBias": obj.get("regionBias"),
            "distanceUnits": obj.get("distanceUnits"),
            "meetingStatesAndProvinces": obj.get("meetingStatesAndProvinces"),
            "meetingCountiesAndSubProvinces": obj.get("meetingCountiesAndSubProvinces"),
            "searchSpecMapCenterLongitude": obj.get("searchSpecMapCenterLongitude"),
            "searchSpecMapCenterLatitude": obj.get("searchSpecMapCenterLatitude"),
            "searchSpecMapCenterZoom": obj.get("searchSpecMapCenterZoom"),
            "numberOfMeetingsForAuto": obj.get("numberOfMeetingsForAuto"),
            "autoGeocodingEnabled": obj.get("autoGeocodingEnabled"),
            "countyAutoGeocodingEnabled": obj.get("countyAutoGeocodingEnabled"),
            "zipAutoGeocodingEnabled": obj.get("zipAutoGeocodingEnabled"),
            "defaultClosedStatus": obj.get("defaultClosedStatus"),
            "enableLanguageSelector": obj.get("enableLanguageSelector"),
            "includeServiceBodyEmailInSemantic": obj.get("includeServiceBodyEmailInSemantic"),
            "bmltTitle": obj.get("bmltTitle"),
            "bmltNotice": obj.get("bmltNotice"),
            "formatLangNames": obj.get("formatLangNames")
        })
        return _obj


